// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF2hcLwvlMeoiTtnL-RqCOzTNONXiLIyE',
    appId: '1:840292034118:web:3342db6bc40ebdff554c47',
    messagingSenderId: '840292034118',
    projectId: 'message-28c2d',
    authDomain: 'message-28c2d.firebaseapp.com',
    storageBucket: 'message-28c2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkwglxkAWwO_KPKdgT-TBwtQ4nsp2PhwA',
    appId: '1:840292034118:android:70267f1eefe6ada4554c47',
    messagingSenderId: '840292034118',
    projectId: 'message-28c2d',
    storageBucket: 'message-28c2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz3XEsIWePboW7BFM0V-6BgEqKyQaKaro',
    appId: '1:840292034118:ios:44de13d78c9580ce554c47',
    messagingSenderId: '840292034118',
    projectId: 'message-28c2d',
    storageBucket: 'message-28c2d.appspot.com',
    androidClientId: '840292034118-olu6g2514ftnv14btlt01vlo40jvdjt0.apps.googleusercontent.com',
    iosClientId: '840292034118-889ihjh1oghrivl18qjkck5oa5h5g4im.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz3XEsIWePboW7BFM0V-6BgEqKyQaKaro',
    appId: '1:840292034118:ios:517ae8003457f666554c47',
    messagingSenderId: '840292034118',
    projectId: 'message-28c2d',
    storageBucket: 'message-28c2d.appspot.com',
    androidClientId: '840292034118-olu6g2514ftnv14btlt01vlo40jvdjt0.apps.googleusercontent.com',
    iosClientId: '840292034118-7fr4c59a1ckj3lcvsg126185ccpvnj75.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp.RunnerTests',
  );
}
